### ISSUE TITLE
metrics error after restart 

### ISSUE THREAD

**Issue by samueltauil** [openshift-evangelists/oc-cluster-wrapper#29] opened 2016-10-20 21:31 UTC
I'm adding tech-preview pipelines feature and restarting the cluster, when I restart it I'm getting this error saying the metrics-deployer already exists:

```
-- Install Metrics ... FAIL
   Error: cannot create metrics deployer service account
   Details:
     Last 10 lines of "origin" container log:
     I1020 17:22:07.618584   18366 docker.go:309] Connecting to docker on unix:///var/run/docker.sock
     I1020 17:22:07.618606   18366 docker.go:329] Start docker client with request timeout=0
     I1020 17:22:07.624222   18366 node.go:138] Connecting to Docker at unix:///var/run/docker.sock
     I1020 17:22:07.684174   18366 manager.go:138] cAdvisor running in container: "/docker/33fe2ae695b70a03252a6f7c1105b83d76f14b9e2d33d2106e1db874c1056d17"
     W1020 17:22:07.738598   18366 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
     I1020 17:22:07.738810   18366 node.go:380] Using iptables Proxier.
     I1020 17:22:07.739019   18366 proxier.go:209] missing br-netfilter module or unset br-nf-call-iptables; proxy may not work as intended
     I1020 17:22:07.739044   18366 node.go:396] Tearing down userspace rules.
     I1020 17:22:07.828102   18366 fs.go:116] Filesystem partitions: map[/dev/vda2:{mountpoint:/var/lib/docker/aufs major:254 minor:2 fsType:ext4 blockSize:0}]
     I1020 17:22:07.880671   18366 create_dockercfg_secrets.go:119] Dockercfg secret controller initialized, starting.

   Caused By:
     Error: serviceaccounts "metrics-deployer" already exists
```

I followed this step to add the pipelines https://docs.openshift.com/container-platform/3.3/install_config/web_console_customization.html#web-console-enable-tech-preview-feature

**Comment by jorgemoralespou** [comment] 2016-10-21 22:00
@samueltauil How are you starting the cluster?
What operating system are u using?

**Comment by samueltauil** [comment] 2016-11-01 03:01
the full command saved on profile/run is: 

```
oc cluster up --public-hostname '127.0.0.1' --host-data-dir '/Users/samueltauil/.oc/profiles/default/data' --host-config-dir '/Users/samueltauil/.oc/profiles/default/config' --routing-suffix '' --use-existing-config --image=registry.access.redhat.com/openshift3/ose --version=v3.3.1.3-1 --skip-registry-check $@ 
``` 
which I'm adding by command line just `--metrics=true` like:
`./oc-cluster up --metrics=true`

**Comment by jorgemoralespou** [comment] 2016-11-03 09:55
This is a "oc cluster up" problem, please report it there.

There's already a bug, although not sure if related: https://github.com/openshift/origin/issues/11207

**Comment by jorgemoralespou** [comment] 2016-11-03 09:57
Can you describe your operating system and if you're using docker machine? 
This tool only works for native docker on mac or linux (although I only test on mac for now), so if using libmachine, probably you better use stock "oc cluster up"

**Comment by jorgemoralespou** [comment] 2017-01-09 10:57
@samueltauil Closing the issue since I can't reproduce. The metrics deployer seem not to be there for that version :-(
Also, I have included some fixes in the code, so maybe worth trying again. If you experience any issue, please open an issue again.

**Closed by jorgemoralespou** 2017-01-09 10:57 UTC
